### ISSUE TITLE
scrappers for upcomming federal elections

### ISSUE THREAD

**Issue by adibender** [adibender/coalitions#113]
- [x] Sachsen
- [x] Brandenburg
- [x] Thüringen

**Comment by bauer-alex** [comment]
On the devel branch, Brandenburg and Thüringen work out well.
For Sachsen sometimes the sample size isn't extracted correctly. For the Infratest polls from 02.07.2019 and 28.08.2018, the function outputs n=100 instead of 1000.

Reason for this is that these instances comprise two blanks after the dot in the `Befragte` field of the Wahlrecht table (only visible when read into R) instead of only one blank.

Base call:
``
scrape_ltw("http://www.wahlrecht.de/umfragen/landtage/sachsen.htm",
           ind_row_remove = -c(1))
``
